version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: SET_YOUR_MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: SET_YOUR_MONGODB_PASSWORD
    volumes:
      - ./data:/data/db
    ports:
      - 32782:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "127.0.0.1:32781:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: SET_YOUR_MONGODB_ADMINUSERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: SET_YOUR_MONGODB_ADMINPASSWORD
